/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function readFileAsync(path: string): Promise<Buffer>
export declare function readFile(path: string): Buffer
export declare function writeFile(path: string, contents: Buffer): void
export declare function writeFileAsync(path: string, contents: Buffer): Promise<void>
